/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_france_jniproject_NdkJniUtil */

#ifndef _Included_com_france_jniproject_NdkJniUtil
#define _Included_com_france_jniproject_NdkJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_france_jniproject_NdkJniUtil
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_france_jniproject_NdkJniUtil_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
